version: "3.8"

services:
  db:
    container_name: libapp-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: library
      MYSQL_USER: huylele
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  lib-app:
    build:
      context: ./server
    container_name: libapp
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://huylele:123456@db:3306/library
  react-app:
    build:
      context: ./client/vite_project
    container_name: react-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["sh", "-c", "cd /app/client/vite_project && npm run dev"]
volumes:
  db-data:
