version: "3.8"

services:
  db:
    container_name: libapp-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: library
      MYSQL_USER: huylele
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  lib-app:
    build: .
    container_name: libapp
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://huylele:123456@db:3306/library
volumes:
  db-data:
