FROM node:15-alpine

WORKDIR /app

COPY package.json package-lock.json ./

# Cài đặt các phụ thuộc của ứng dụng
RUN npm ci
# --lockfile-version 3

# Sao chép toàn bộ mã nguồn của ứng dụng vào thư mục làm việc
COPY . .

# Mở cổng 3000 để truy cập ứng dụng ReactJS
EXPOSE 3000

# Khởi động ứng dụng ReactJS
#ENTRYPOINT ["npm", "run", "dev"]
ENTRYPOINT ["sh", "-c", "cd /app/client/vite_project && npm run dev"]
#ENTRYPOINT ["tail", "-f", "/dev/null"]
