version: "3.8"

services:
  react-app:
    build: .
    container_name: react-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: dev
