FROM node:14-alpine

WORKDIR /app

COPY package*.json ./

#cài typescript
RUN npm install -g typescript

# Cài đặt các phụ thuộc của ứng dụng
RUN npm install --lockfile-version 3

# Sao chép toàn bộ mã nguồn của ứng dụng vào thư mục làm việc
COPY . .

#build
RUN npm run build

# Mở cổng 3000 để truy cập ứng dụng ReactJS
EXPOSE 3000

# Khởi động ứng dụng ReactJS
ENTRYPOINT ["npm", "run", "dev"]
